#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
#include <time.h>
#include <fstream>
#include <sstream>
using std::cout;
using std::cin;
using std::endl;

using std::left;
using std::right;
using std::setw;
using std::copy;
using std::setprecision;
using std::string;
using std::flush;
using std::sort;
using std::vector;
using std::getline;
using std::fixed;
using std::ifstream;
using std::getline;
using std::istringstream;
using std::ofstream;
using std::stringstream;
