#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
using std::cout;
using std::cin;
using std::endl;

using std::left;
using std::right;
using std::setw;
using std::copy;
using std::setprecision;
using std::string;
using std::flush;
using std::sort;
using std::vector;
