#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
#include <time.h>
#include <fstream>
#include <chrono>
#include <omp.h>
#include<random>
using std::partition;
#include <execution>
#include<list>
using std::list;
#include<deque>
using std::count;
using std::deque;
using std::move;
#include <thread>
using std::thread;
using std::cout;
using std::cin;
using std::ios;
using std::endl;
using std::back_inserter;
using std::left;
using std::right;
using std::setw;
using std::copy;
using std::setprecision;
using std::string;
using std::flush;
using std::sort;
using std::vector;
using std::getline;
using std::fixed;
using std::stringstream;
using std::runtime_error;
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::istringstream;
using std::move;